name: receipt_reader_app
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  fl_chart: ^0.68.0
  sqflite: ^2.2.7+4
  path_provider: ^2.0.11
  path: ^1.8.2
  camera: ^0.11.0+1
  google_mlkit_text_recognition: ^0.13.0
  http: ^1.2.1
  image_picker: ^1.1.2
  intl: ^0.17.0

flutter:
  uses-material-design: true
